### ISSUE TITLE
Can this open source code be changed to run on Kaist Urban Datasets? I can't use ORB_SLAM3 source code on this data

### ISSUE THREAD

**Issue by Bob-zjy** [geoeo/ORB_SLAM3_V1.0#1]

**Comment by geoeo** [comment]
Yes it can. Running is not very streamlined you have to change the hardcoded values in https://github.com/geoeo/ORB_SLAM3_V1.0/blob/master/catkin_ws/src/mono-interial/src/mono-interial_node.cpp

**Comment by Bob-zjy** [comment]
> Yes it can. Running is not very streamlined you have to change the hardcoded values in https://github.com/geoeo/ORB_SLAM3_V1.0/blob/master/catkin_ws/src/mono-interial/src/mono-interial_node.cpp

ok ok  thank you !!
